---
language: php
addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    - empty-expect

cache:
  directories:
    - $HOME/.composer/cache/files

php: # symfony/skeleton requires ^7.0.8
- nightly
- 7.2
- 7.1
- 7.0 # SYMFONY_VERSION="^3.4" only one version of skeleton working with php 7.0

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: DRUPAL_VERSION="@alpha"
  allow_failures:
  - php: 7.0 # sensiolabs/security-checker 4.1.7
  - php: 7.3
  - php: nightly
  - env: DRUPAL_VERSION="@alpha"

before_install:
- install --directory .travis/bin
- wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker

# - pip install pygments # but now pygmentize is no more used right here.
- go get -u github.com/jingweno/ccat

install:
#  drupal/drupal is dowloaded directly from GitHub, because alpha versions where not posted on packagist for version 8.5.0-alpha1
- composer create-project --no-install --repository='{"type":"vcs", "url":"https://github.com/drupal/drupal", "no-api":true}' drupal/drupal my-project $DRUPAL_VERSION
- cd my-project
- composer install

before_script:
- composer show
- composer why symfony/http-foundation
- $GOPATH/bin/ccat composer.json
# - bin/console
- ls --color
- ls --color vendor
- ls --color vendor/bin

script:
- sleep .01
# - elinks http://localhost:8000/ -dump-color-mode 4 -dump

- php ../.travis/bin/security-checker --version
- php ../.travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
- 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock'
  #^ This checks that the application doesn't use dependencies with known security vulnerabilities
